# Site settings
title: Programming the Computer ğŸ‘¨â€ğŸ’»
name: Programming the Computer
author: Daniel SchÃ¼tte
email: d.schuette@online.de
description: Bits and pieces about programming.
baseurl: ""
url: "https://danielschuette.github.io/"
twitter_username: DogtorDash
github_username:  DanielSchuette

# Build settings
markdown: kramdown
theme: minima
#remote_theme: b2a3e8/jekyll-theme-console

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Configs used by `jekyll-theme-console' (if enabled)
#header_pages:
#  - index.md
#  - about.md
#  - links.md
#  - shell.md
#  - compiler.md
#
#footer: 'Follow me on <a href="https://github.com/DanielSchuette">GitHub</a>.'
