# Site settings
title: Programming the Computer ğŸ‘¨â€ğŸ’»
name: Programming the Computer
author: Daniel SchÃ¼tte
email: d.schuette@online.de
description: Bits and pieces about programming.
baseurl: ""
url: "https://danielschuette.github.io/"
twitter_username: DogtorDash
github_username:  DanielSchuette
linkedin_username: daniel-schuette
google_analytics: "UA-118902218-1"
show_excerpts: false

# Build settings
markdown: kramdown
theme: minima

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

disqus:
  shortname: https-danielschuette-github-io
